# Generated by Django 5.2.6 on 2025-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('emisor', models.CharField(blank=True, max_length=255, verbose_name='Emisor')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/', verbose_name='Imagen')),
                ('enlace_externo', models.URLField(blank=True, null=True, verbose_name='Enlace externo')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/archivos/', verbose_name='Archivo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden (mayor valor primero)')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-orden', '-fecha'],
            },
        ),
    ]
