# Generated by Django 5.2.6 on 2025-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tecnologias', models.CharField(help_text='Ejemplo: HTML, CSS, JS, Django', max_length=200)),
                ('enlace_codigo', models.URLField(blank=True, null=True)),
                ('enlace_proyecto', models.URLField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
            ],
        ),
    ]
